### ISSUE TITLE
Index Error from prokka2kegg_batch.py

### ISSUE THREAD

**Issue by GeoMicroSoares** [SilentGene/Bio-py#1]
Hi there,

Using `prokka2kegg_batch.py` I'm getting the following error:
```
Traceback (most recent call last):
  File "prokka2kegg_batch.py", line 183, in <module>
    main()
  File "prokka2kegg_batch.py", line 177, in main
    mapping_array = gbk_parser(in_path)
  File "prokka2kegg_batch.py", line 63, in gbk_parser
    uniprotkb = pattern_uniprotkb.findall(line)[0]
IndexError: list index out of range
```

Any ideas? Running the command as it's supposed to I hope:
```
$ python3 prokka2kegg_batch.py -i pangenomes_gbk/ -d idmapping_KO.tab.gz -o ./pangenomes_gbk_kegg/
```

EDIT: This is also replicated with the other script:
```
$ python3 prokka2kegg.py -i pangenomes_gbk/pangenome.gbk -d idmapping_KO.tab.gz -o output.txt
Traceback (most recent call last):
  File "prokka2kegg.py", line 160, in <module>
    main()
  File "prokka2kegg.py", line 154, in main
    mapping_array = gbk_parser(args.i)
  File "prokka2kegg.py", line 61, in gbk_parser
    uniprotkb = pattern_uniprotkb.findall(line)[0]
IndexError: list index out of range
```

**Comment by SilentGene** [comment]
Hi André,
What version of `prokka` did you use to generate these `*.gbk` files? I used version 1.14, and there is something like:

>                     /inference="similar to AA sequence:UniProtKB:P0ABQ0"

This script will try to capture the ID after the `UniProtKB:`, but it seems like it failed to find this pattern in your gbk files.

**Comment by GeoMicroSoares** [comment]
Hi there,

Using prokka v.1.13.3 but by grepping my file this comes out though:
```
/inference="similar to AA sequence:UniProtKB:P77223"
```

**Comment by SilentGene** [comment]
Hi André, I have uploaded a sample gbk file in the repo, would you mind to have a try in your environment using command:
```bash
python3 prokka2kegg.py -i sample.gbk -d idmapping_KO.tab.gz -o sample.kegg.out.txt
```
And see if the result could be generated successfully.

**Comment by GeoMicroSoares** [comment]
Hi there,

Just did and ran normally!

```
$ head sample.kegg.out.txt
AHCGDBLN_00001  K05685
AHCGDBLN_00002  K10804
AHCGDBLN_00003
AHCGDBLN_00004
AHCGDBLN_00005
AHCGDBLN_00006
AHCGDBLN_00007
AHCGDBLN_00008
AHCGDBLN_00009
AHCGDBLN_00010
```

**Comment by SilentGene** [comment]
Hi André, I think it should be an incompatibility problem of your file format. If you don't mind, sending your gbk file or a small subset of that to me (heyu.lin@student.unimelb.edu.au) will help me dig out what's going on there, otherwise, you should compare your gbk file and my sample gbk file to figure out this.

**Comment by SilentGene** [comment]
Hi André, Thanks for your data. I have fixed the problem. The gbk file you provided contains some insertion sequences described by:

> /inference="similar to AA sequence:ISfinder:ISPa38"

which wasn't recognized by my script. I fixed this now. Please download the current version and try again.

Cheers,
Heyu
