### ISSUE TITLE
Why did the new version of prokka2kegg delete the KO info?

### ISSUE THREAD

**Issue by dangchenyuan** [SilentGene/Bio-py#2]
Now, I want to get the KO info from the prokka result, what should I do? Or can I just only use the old version to get the KO info?

**Comment by SilentGene** [comment]
hi Chenyuan,

The cross-reference database used by prokka2kegg was provided by Uniprot. Unfortunately, Uniprot has removed the KO info from the database since a recent update. Therefore, users have to download my formatted database from my repo to run the script.

Cheers,
Heyu

**Comment by SilentGene** [comment]
We can discuss you questions via email. My email address is heyu.lin@student.unimelb.edu.au.
