### ISSUE TITLE
BLASTp warnings in POCP-matrix.py

### ISSUE THREAD

**Issue by RiescoR** [SilentGene/Bio-py#3]
Is there a way to silence BLASTp warnings in POCP-matrix.py? it generates a bazillion messages like "Warning: [Query 3937-3968] Examining 5 or more matches is recommended"

**Comment by SilentGene** [comment]
Unfortunately, BLAST issues a warning when users use the `-max_target_seqs 1` parameter, and it cannot be disabled. However, I might be able to redirect all blastp warnings to a file if you find it annoying to see them printed on your console...

**Comment by RiescoR** [comment]
It's not really that annoying, I understand the need of the -max_target_seqs 1. I was just wandering if there was a way to limit the warnings, but it's ok. Maybe it would be nice to add a disclaimer in the readme, just to tell people that is not a problem of the py command, or as you suggest redirect those specific console outputs out.

**Comment by SilentGene** [comment]
Thanks for the suggestion, I'll make some modifications very soon:)

**Comment by SilentGene** [comment]
The new version will discard the specific warnings. Give it a try:)

**Comment by RiescoR** [comment]
That´s great! thank you :)
