### ISSUE TITLE
How to know which specific sequences are removed from the "remove_duplicate_seqs" python script  ?

### ISSUE THREAD

**Issue by nguyenvantuananh99** [SilentGene/Bio-py#4]
Dear author,

Thank you so much for your valuable python script to solve the "duplicate sequences in genome fasta file by IDs or sequences itself". 
https://github.com/SilentGene/Bio-py/tree/master/remove_duplicate_seqs 

I just want to ask you a question in your script:
How to know which specific sequences are removed from this script ?
I want to have a list of IDs or sequences are filtered in separate file, just in case I want to check the accuracy of filtered sequences. 

Thank you so much for clarify my question.

**Comment by SilentGene** [comment]
Sorry, this script doesn't include this function, and adding it would be hard due to the way the script operates. However, you can use the following bash command to check for sequences that are present in the first file but not in the second file
```
comm -23 <(grep '^>' seq1.fa | sort) <(grep '^>' seq2.fa | sort)
```
I hope that helps!
